# The messages for showing recipes. Replace numbers with %d and item names with %s.
# Header string ("Recipe for Solar Panel"). Defaults to "&eRecipe for %s:"
header-string: "&e&nRecipe for %s:"
# The messages for showing recipes with an amount. Replace numbers with %d, item names with %s, and amount with %d.
# Header string ("Recipe for 64 Solar Panel"). Defaults to "&eRecipe for %d %s:"
header-amount-string: "&e&nRecipe for %d %s:"
# Stack string ("(20 x64 + 32)"). Provides an easier access to numbers, defaults to "&e%d (%d x%d + %d)"
stack-string: "&e%d (%d x%d + %d)"
# Amount string ("200 of Copper Dust"). Defaults to "%s of %s".
amount-string: "&e%s of %s"
# Needed string ("10 more Silicon needed"). Defaults to "&e%s more %s needed"
needed-string: "&e%s more %s needed"
# Item not found string ("That item was not found."). Defaults to "&cThat item was not found."
no-item-string: "&cThat item was not found."
# Not a number string ("That's not a number!"). Defaults to "&cThat's not a number!"
not-a-number-string: "&cThat's not a number!"
# Too many categories/items strings
# ("That many categories/items is not supported yet. Please use the command form of the calculator.").
# Defaults to "&cThat many categories/items is not supported yet. Please use the command form of the calculator.".
category-error-string: "&cThat many categories is not supported yet. Please use the command form of the calculator."
item-error-string: "&cThat many items is not supported yet. Please use the command form of the calculator."
# Not a player string ("You must be a player to send this message!").
# Defaults to "&cYou must be a player to send this message!"
not-a-player-string: "&cYou must be a player to send this message!"
# Invalid number string ("Invalid number!").
# Defaults to "&cInvalid number!"
invalid-number-string: "&cInvalid number!"
